import React from 'react';

const IndexSectionCustomComponents4: React.FC = () => {
    return (
        <section id="insights" className="bg-linear-to-b from-[#eef2ff] to-[#dbe6ff] py-20 lg:py-28">
  <div className="mx-auto max-w-7xl px-6 lg:px-8">
    <div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
      <div className="mx-auto max-w-sm">
        <div className="overflow-hidden rounded-[2.25rem] bg-[#1a0b4e] p-5 text-white shadow-2xl shadow-violet-900/20">
          <div className="rounded-[1.75rem] border border-white/10 bg-linear-to-b from-violet-900/80 to-[#1a0b4e] p-6">
            <p className="text-xs uppercase tracking-[0.3em] text-violet-200">Mobile Experience</p>
            <h2 className="mt-4 font-heading text-4xl font-bold leading-tight">
              <span>Make Faster, Smarter Investment Decisions</span>
            </h2>
            <p className="mt-4 text-sm leading-7 text-violet-100/80">The truly live leading real estate numbers for approved predictions.</p>
            <a href="#contact" className="mt-6 inline-flex rounded-full bg-violet-600 px-5 py-3 text-sm font-semibold text-white">Book a Call</a>
          </div>
          <div className="mt-5 rounded-3xl bg-white p-4 text-slate-900">
            <div className="mb-4 flex items-center justify-between">
              <p className="font-semibold">BulBAI</p>
              <span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-semibold text-violet-700">Investments</span>
            </div>
            <div className="space-y-3">
              <div className="rounded-xl bg-slate-50 p-3">
                <p className="text-sm font-semibold">What next over time</p>
                <p className="mt-1 text-xs text-slate-500">Scenario forecast generated by AI</p>
              </div>
              <div className="rounded-xl bg-slate-50 p-3">
                <p className="text-sm font-semibold">Report export ready</p>
                <p className="mt-1 text-xs text-slate-500">Board-level summaries in seconds</p>
              </div>
              <div className="rounded-xl bg-slate-50 p-3">
                <p className="text-sm font-semibold">Settings</p>
                <p className="mt-1 text-xs text-slate-500">Granular permissions and inputs</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div className="inline-flex rounded-full border border-slate-300 bg-white/70 px-4 py-2 text-sm font-semibold text-brand backdrop-blur">Immersive AI SaaS redesign</div>
        <h2 className="mt-6 max-w-2xl font-heading text-4xl font-bold leading-tight text-brand lg:text-5xl">
          <span>A stronger digital presence for your portfolio</span>
        </h2>
        <p className="mt-6 max-w-2xl text-lg leading-8 text-brand-muted">This redesign turns the original site into a premium AI SaaS experience tailored for your portfolio: cinematic gradients, intelligent dashboards and clearer conversion points that make your work feel enterprise-ready.</p>
        <div className="mt-10 grid gap-5 sm:grid-cols-2">
          <div className="rounded-[1.75rem] bg-white/80 p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-100 text-violet-700">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="h-6 w-6">
                <path d="M4 5h16v2H4V5zm0 6h10v2H4v-2zm0 6h16v2H4v-2z" />
              </svg>
            </div>
            <h3 className="font-heading text-xl font-bold text-brand">
              <span>Cleaner messaging</span>
            </h3>
            <p className="mt-3 text-sm leading-7 text-brand-muted">Sharper product language around analytics, forecasting and decision support to immediately explain what BulBAI does.</p>
          </div>
          <div className="rounded-[1.75rem] bg-white/80 p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-700">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="h-6 w-6">
                <path d="M12 3l8 4v6c0 5-3.4 8.7-8 10-4.6-1.3-8-5-8-10V7l8-4z" />
              </svg>
            </div>
            <h3 className="font-heading text-xl font-bold text-brand">
              <span>Trust-first presentation</span>
            </h3>
            <p className="mt-3 text-sm leading-7 text-brand-muted">Brand signals, platform snapshots and structured content that reinforce enterprise credibility for clients and recruiters alike.</p>
          </div>
          <div className="rounded-[1.75rem] bg-white/80 p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-100 text-sky-700">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="h-6 w-6">
                <path d="M5 3h14a2 2 0 012 2v14l-4-3-4 3-4-3-4 3V5a2 2 0 012-2z" />
              </svg>
            </div>
            <h3 className="font-heading text-xl font-bold text-brand">
              <span>Portfolio-ready showcase</span>
            </h3>
            <p className="mt-3 text-sm leading-7 text-brand-muted">A more advanced UI language that better demonstrates product thinking, visual hierarchy and SaaS design maturity.</p>
          </div>
          <div className="rounded-[1.75rem] bg-white/80 p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="h-6 w-6">
                <path d="M3 12l7-7 4 4 7-7v19H3V12z" />
              </svg>
            </div>
            <h3 className="font-heading text-xl font-bold text-brand">
              <span>Higher conversion intent</span>
            </h3>
            <p className="mt-3 text-sm leading-7 text-brand-muted">Strategic call-to-action placement and immersive visuals that naturally guide visitors toward booking a call.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


    );
};

export default IndexSectionCustomComponents4;